name: Econ
version: 0.1
author: Tempoo50
main: de.tempoo50.eco.main.Eco

commands:

   eco:
      description:
   pay:
      description:
   set:
      description:
   payall:
      description: